spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_market?serverTimezone=Asia/Seoul
    username: 'campus_user'
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB # 사진 업로드를 위한 설정
      max-request-size: 10MB

file:
  upload-dir: /Users/bagjuyun/campus_market_uploads/